# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bd2efa3ad0be0ba76fb9434c5cac889a872f9ddb01b77ac2c09c1e0606a91528a5496f3ea0ac86a03444c352ed30fd5061ca31288863b1a87635856363d9703

test:
  secret_key_base: 39bc0ddf871c5502cfba9d5db43b0ba32e8700698671e29e9ffffbf5866b7b36607d9a32b59dbcedde3701ba26d36fa2e4d26cca31ef8c615ffe29bd3cf4ded6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
